name: Python Docker Host Runner

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build Docker image
        run: sudo docker build -f Dockerfile -t notions_slack_bot_docker_image .
        working-directory: .

      - name: Stop previous Docker container
        run: sudo docker stop notions_slack_bot_docker_container || true
        continue-on-error: true

      - name: Remove previous Docker container
        run: sudo docker rm notions_slack_bot_docker_container || true
        continue-on-error: true
      - name: Run Docker container
        run: |
          sudo docker run -d --name notions_slack_bot_docker_container \
          -e SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }} \
          -e SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }} \
          notions_slack_bot_docker_image